version: '3.8'

services:
  # خدمة التطبيق (Atheer Switch)
  app:
    build: .
    ports:
      - "4000:4000"
    env_file:      # <--- أضف هذا السطر

      - .env
    environment:
      - PORT=4000
      - NODE_ENV=development
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=atheer_switch
      - DB_USER=postgres
      - DB_PASS=postgres
      - DB_SSL=false
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_TLS=false
      - ADMIN_API_KEY=local_dev_admin_key_only_not_for_prod
      - JEEB_API_URL=http://host.docker.internal:8000/api/v1/jeeb # استخدم host.docker.internal للوصول للخادم المحلي من داخل الحاوية
      - JEEB_AGENT_WALLET=wallet_id_from_jeeb
      - JEEB_API_KEY=jeeb_api_key
    depends_on:
      - postgres
      - redis
    networks:
      - atheer-network

  # قاعدة البيانات (PostgreSQL)
  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=atheer_switch
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - atheer-network

  # التخزين المؤقت (Redis)
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - atheer-network

networks:
  atheer-network:
    driver: bridge

volumes:
  postgres_data:
  redis_data:
